### ISSUE TITLE
Weird exception I cant understang

### ISSUE THREAD

**Issue by TimurVa** [GLOKON/guacamole-common-js#4]
Can you please tell me what I'm doing wrong? I'm using Angular 16 in such a way
import { HTTPTunnel } from '@glokon/guacamole-common-js';

Error: export 'HTTPTunnel' (imported as 'HTTPTunnel') was not found in '@glokon/guacamole-common-js' (possible exports: default)

**Comment by DanielMcAssey** [comment]
Hey! So we don't currently export named modules, you would need to import as follows

```
import Guacamole from '@glokon/guacamole-common-js';
new Guacamole.HTTPTunnel();
```

Open to a PR that supports named modules in exports.

**Comment by TimurVa** [comment]
Morning, yeah, somehow I've figured it out, thank you

**Comment by codebling** [comment]
See also #7.

README shows an example using named exports, so it is weird that they are not there. 
>  import { Client, Tunnel } from '@glokon/guacamole-common-js';

**Comment by DanielMcAssey** [comment]
Ah yeah, that README isnt quite right, I need to build a rollup script that merges the JS files and creates the named exports.
Havent had time to do that yet, but the plan is there, which is why the README has that

**Comment by codebling** [comment]
For everyone still landing on this, now that #7 is merged, 
```
 import { HTTPTunnel } from '@glokon/guacamole-common-js';
```
should work as expected
